DROP TABLE LIBRARY_BORROWS CASCADE;

DROP TABLE LIBRARY_RESERVES CASCADE;

DROP TABLE LIBRARY_COPY CASCADE;

DROP TABLE LIBRARY_INV_EDITOR CASCADE;

DROP TABLE LIBRARY_JOURNAL_ISSUE CASCADE;

DROP TABLE LIBRARY_JOURNAL_VOLUME CASCADE;

DROP TABLE LIBRARY_PROCEEDINGS CASCADE;

DROP TABLE LIBRARY_WRITES CASCADE;

DROP TABLE LIBRARY_BOOK CASCADE;

DROP TABLE LIBRARY_DOCUMENT CASCADE;

DROP TABLE LIBRARY_READER CADCADE;

DROP TABLE LIBRARY_BRANCH CASCADE;

DROP TABLE LIBRARY_PUBLISHER CASCADE;

DROP TABLE LIBRARY_CHIEF_EDITOR CASCADE;

DROP TABLE LIBRARY_AUTHOR CASCADE;
